# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2020-01-31 09:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classroom', models.CharField(db_column='classroom', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='CreateStu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_column='name', max_length=10)),
                ('classroom', models.CharField(db_column='classroom', max_length=20)),
                ('sex', models.IntegerField(db_column='sex')),
            ],
            options={
                'db_table': 'laolao',
            },
        ),
    ]
