# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2020-02-02 07:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('one', '0002_auto_20200131_1000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createstu',
            name='classroom',
            field=models.CharField(db_column='classroom', max_length=20),
        ),
        migrations.DeleteModel(
            name='Class',
        ),
    ]
